// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
       // return ios;
      case TargetPlatform.macOS:
        //return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNArho4VuW4IGCVfZ27Ac-f-w6TWdPhHo',
    appId: '1:100181594028:web:2dc153492ef24fcbb57409',
    messagingSenderId: '100181594028',
    projectId: 'parcialflutter2',
    authDomain: 'parcialflutter2.firebaseapp.com',
    storageBucket: 'parcialflutter2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbB6PCTMOXmSJlmoVpB_QtGI-UbgATGc',
    appId: '1:100181594028:android:d7677199de8a4a4bb57409',
    messagingSenderId: '100181594028',
    projectId: 'parcialflutter2',
    storageBucket: 'parcialflutter2.appspot.com',
  );
/*
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0jaPmKvAxGX9SfaDZPxT4Ia41yiuMOYI',
    appId: '1:100181594028:ios:5d15af8a1070bbf12a04d5',
    messagingSenderId: '100181594028',
    projectId: 'parcialflutter2',
    storageBucket: 'parcialflutter2.appspot.com',
    iosClientId: '100181594028-9cvv3s4cvnlmljau3n81l96tirhf959j.apps.googleusercontent.com',
    iosBundleId: 'flutterutec.edu.sv.flutterFirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0jaPmKvAxGX9SfaDZPxT4Ia41yiuMOYI',
    appId: '1:100181594028:ios:5d15af8a1070bbf12a04d5',
    messagingSenderId: '100181594028',
    projectId: 'parcialflutter2',
    storageBucket: 'parcialflutter2.appspot.com',
    iosClientId: '100181594028-9cvv3s4cvnlmljau3n81l96tirhf959j.apps.googleusercontent.com',
    iosBundleId: 'flutterutec.edu.sv.flutterFirebaseapp',
  );*/
}
